# Sprint 3 Tarea M3 T01
## Ejercicio 1
**Crea una función que dado un Array de una dimensión, te haga un resumen estadístico básico de los datos. Si detecta que el array tiene más de una dimensión, tiene que mostrar un mensaje de error.**

In [4]:
import numpy as np

def resumen_estat(array):
    if array.ndim > 1:
        print("Error: El array tiene más de una dimensión.")
        return
    
    print("\nResumen estadístico:")
    print("Número de elementos:", array.size)
    print("Valor mínimo:", np.min(array))
    print("Valor máximo:", np.max(array))
    print("Media:", np.mean(array))
    print("Mediana:", np.median(array))
    print("Desviación estándar:", np.std(array))

    
datos = np.array([1, 2, 3, 4, 5])
resumen_estat(datos)



Resumen estadístico:
Número de elementos: 5
Valor mínimo: 1
Valor máximo: 5
Media: 3.0
Mediana: 3.0
Desviación estándar: 1.4142135623730951


## Ejercicio 2
**Crea una función que te genere un cuadrado NxN de números aleatorios entre el 0 y el 100.**

In [5]:
import numpy as np

N = int(input("¿Cuál es el valor de N? "))

def matriz_nxn(n):
    array = np.random.randint(0, 101, size=(n, n))
    return(array)
    
matriz_prueba = matriz_nxn(N)
print(matriz_prueba)

¿Cuál es el valor de N? 5
[[37  8  0 77 17]
 [21 45 55 76 50]
 [45 71 77 61 62]
 [49 11 10 41 37]
 [29  7  0 80 95]]


## Ejercicio 3
**Crea una función que dada una tabla de dos dimensiones (NxM), te calcule los totales por fila y los totales por columna.**

In [6]:
import numpy as np

def suma_filas_y_columnas(matriz):
    print("\nLa suma de las filas son:", np.sum(matriz, axis=1))
    print("La suma de las columnas son:", np.sum(matriz, axis=0))

suma_filas_y_columnas(matriz_prueba)


La suma de las filas son: [139 247 316 148 211]
La suma de las columnas son: [181 142 142 335 261]


## Exercici 4
**Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.**

In [8]:
import numpy as np

def matriz_de_correlacion(matriz):
    matriz_np = np.array(matriz)
    media_columnas = np.mean(matriz_np, axis=0)
    desviacion_estandar_columnas = np.std(matriz_np, axis=0)
    matriz_normalizada = (matriz_np - media_columnas) / desviacion_estandar_columnas
    num_columnas = matriz_normalizada.shape[1]
    matriz_correlacion = np.zeros((num_columnas, num_columnas))

    for i in range(num_columnas):
        for j in range(i, num_columnas):
            producto_punto = np.dot(matriz_normalizada[:, i], matriz_normalizada[:, j])
            matriz_correlacion[i, j] = producto_punto / (matriz_normalizada.shape[0])
            matriz_correlacion[j, i] = matriz_correlacion[i, j]
            matriz_correlacion = np.abs(matriz_correlacion)

    return matriz_correlacion

resultado = matriz_de_correlacion(matriz_prueba)
print(resultado)


[[1.         0.02871462 0.0187272  0.81441246 0.30770743]
 [0.02871462 1.         0.99231144 0.07301108 0.13424064]
 [0.0187272  0.99231144 1.         0.09830143 0.11651035]
 [0.81441246 0.07301108 0.09830143 1.         0.27406732]
 [0.30770743 0.13424064 0.11651035 0.27406732 1.        ]]
